[package]
name = "rust-react"
version = "0.1.0"
edition = "2021"


[dependencies]
derive_more = { version = "1.0.0", features = ["debug", "from"] }
rust-react-template = { path = "./template" }

[workspace]
members = ["template"]
